### ISSUE TITLE
npm-safe-install <some-new-package> removes previously installed dependencies from node_modules/

### ISSUE THREAD

**Issue by cirosantilli** [UD-UD/npm-safe-install#4]
Full use case described at: https://stackoverflow.com/questions/59389027/how-to-interactively-test-the-executable-of-an-npm-node-js-package-during-develo

Not 100% sure that this package is meant to cover that use case.

**Comment by Venryx** [comment]
The issue seems to be that `npm-safe-install` does not delete the symlinks prior to running `npm install`.

This means that `npm install` runs with the old symlinks still present. Even though `npm-safe-install` re-adds the symlinks afterward, that's not good enough, because the `npm install` command itself "tunnels into" the symlinked folders and deletes the dependencies' subdependencies.

Now why would `npm install` tunnel into symlinked dependencies and deletes some of its sub-dependencies? Well, I think it's because it's trying to de-duplicate certain packages that are dependencies of both the root project as well as the symlinked packages.

For example:
Root) my-web-app
Root.Dep1) typescript@3
Root.Dep2) my-library (sym-linked)
Root.Dep2.Dep1) typescript@3

When `npm-safe-install` runs, apparently:
1) NSI runs `npm install`; this breaks the symlink to `my-library`, however...
2) NSI then restores the symlink for the `my-library` package.

The problem is that in step 1, `npm install` tunnels into the `my-library` dependency (`Root.Dep2`) and sees that it has the `typescript@3` package as a subdependency (`Root.Dep2.Dep1`). However, npm doesn't like this, because it sees that the package already exists as a direct dependency of the root project (`Root.Dep1`), so it deletes it.

### Solution

A way to fix this would seem to be to just delete the symlinked folders prior to running `npm install`:
1) Scan the root project's `node_modules` folder for any symlinked dependencies.
2) Delete the symlinked dependency folders, to protect their subdependencies from getting modified by the next step...
3) Run `npm install`. Because we deleted the symlinked folders, npm won't mess with their subdependencies.
4) Recreate the symlinks to those dependency folders.

@UD-UD Does this seem like a workable solution to you?

Like the OP, I've encountered this annoyance many times over the months, so it would be awesome of this package could solve both the symlink recreation process, as well as the "protect the subdependencies of symlinked folders" as a pre-step.

**Comment by Venryx** [comment]
Also, do you have time available to work on the above fix? If not, would you be willing to review/accept a pull request adding the fix?

If you can't get back in a few days, I may get impatient and go ahead and create a new fork/npm-package. XD (Which is okay, though it's preferable to keep the library non-fragmented of course.)

**Comment by UD-UD** [comment]
@Venryx Sure this solution works. Currently I don't have enough time to work on this. 
Feel free to Send a  PR with the said fix. I will merge and publish the same as soon as possible.

Thanks.

**Comment by Venryx** [comment]
Just finished the PR! (https://github.com/UD-UD/npm-safe-install/pull/5)

Confirmed working in my project.

**Comment by Venryx** [comment]
Fixed a few more bugs discovered from usage in a project with symlinked organization packages (eg. `@babel/core`):
* Fixed that packages underneath an organization folder (eg. "@webpack/") were not getting restored properly. (it would try to restore "package-name" by itself, instead of "@org-name/package-name")
* Made so that if command fails, it logs the actual reason/error!
* Made so that if there are no packages to relink after the "npm install" command, the "npm link" command is not even run. (else, the `npm link X Y Z` is just `npm link`, which has a different and unexpected behavior)
